local options = { noremap = true, silent = true }
vim.cmd([[ let mapleader = " " ]])
vim.keymap.set('i', 'jk', '<ESC>', options)
vim.keymap.set('t', 'jk', '<C-\\><C-n>', options)
vim.keymap.set('n', '<leader>l', ':vertical resize -5<CR>', options)
vim.keymap.set('n', '<leader>h', ':vertical resize +5<CR>', options)
vim.keymap.set('n', '<leader>j', ':resize -5<CR>', options)
vim.keymap.set('n', '<leader>k', ':resize +5<CR>', options)
vim.keymap.set('n', '<C-x>', ':noh<CR>', options)
vim.keymap.set("n", "<C-d>", "<C-d>zz", options)
vim.keymap.set("n", "<C-u>", "<C-u>zz", options)
-- vim.keymap.set("n", "<C-n>", ":Ex<CR>", options)
