source <sfile>:h/init/options.vim
source <sfile>:h/init/plugins.vim
source <sfile>:h/init/colorscheme.vim
source <sfile>:h/init/keymaps.vim
source <sfile>:h/init/telescope.vim
source <sfile>:h/init/lsp.vim
source <sfile>:h/init/treesitter.vim
source <sfile>:h/init/coc.vim
source <sfile>:h/init/nerdtree.vim
source <sfile>:h/init/test.vim
source <sfile>:h/init/general.vim
source <sfile>:h/init/bufferline.vim
source <sfile>:h/init/lualine.vim
source <sfile>:h/init/git.vim
