return {}
-- return {
-- 	"yetone/avante.nvim",
-- 	event = "VeryLazy",
-- 	version = false,
-- 	build = "make",
-- 	opts = {
-- 		provider = "claude",
-- 		providers = {
-- 			openai = {
-- 				endpoint = "https://api.openai.com/v1",
-- 				model = "gpt-4o",
-- 				timeout = 30000,
-- 				extra_request_body = {
-- 					temperature = 0,
-- 					max_tokens = 8192,
-- 				},
-- 			},
-- 			claude = {
-- 				endpoint = "https://api.anthropic.com",
-- 				model = "claude-sonnet-4-20250514",
-- 				timeout = 30000,
-- 				extra_request_body = {
-- 					temperature = 0.75,
-- 					max_tokens = 20480,
-- 				},
-- 			},
-- 		},
-- 	},
-- 	dependencies = {
-- 		"stevearc/dressing.nvim",
-- 		"nvim-lua/plenary.nvim",
-- 		"MunifTanjim/nui.nvim",
-- 		--- The below dependencies are optional,
-- 		"echasnovski/mini.pick", -- for file_selector provider mini.pick
-- 		"ibhagwan/fzf-lua", -- for file_selector provider fzf
-- 		{
-- 			-- support for image pasting
-- 			"HakonHarnes/img-clip.nvim",
-- 			event = "VeryLazy",
-- 			opts = {
-- 				-- recommended settings
-- 				default = {
-- 					embed_image_as_base64 = false,
-- 					prompt_for_file_name = false,
-- 					drag_and_drop = {
-- 						insert_mode = true,
-- 					},
-- 					-- required for Windows users
-- 					use_absolute_path = true,
-- 				},
-- 			},
-- 		},
-- 		{
-- 			-- Make sure to set this up properly if you have lazy=true
-- 			"MeanderingProgrammer/render-markdown.nvim",
-- 			opts = {
-- 				file_types = { "markdown", "Avante" },
-- 			},
-- 			ft = { "markdown", "Avante" },
-- 		},
-- 	},
-- 	config = function(_, opts)
-- 		require("avante").setup({
-- 			opts = opts,
-- 			-- system_prompt as function ensures LLM always has latest MCP server state
-- 			-- This is evaluated for every message, even in existing chats
-- 			system_prompt = function()
-- 				local hub = require("mcphub").get_hub_instance()
-- 				return hub and hub:get_active_servers_prompt() or ""
-- 			end,
-- 			-- Using function prevents requiring mcphub before it's loaded
-- 			custom_tools = function()
-- 				return {
-- 					require("mcphub.extensions.avante").mcp_tool(),
-- 				}
-- 			end,
-- 		})

--         -- call :AvanteSwitchProvider openai
--         vim.cmd("AvanteSwitchProvider claude")

-- 		local mark = require("harpoon.mark")
-- 		vim.keymap.set("n", "<leader>af", mark.add_file, { noremap = true, silent = true })
-- 		vim.keymap.set("n", "<leader>ai", ":AvanteToggle<cr>", { noremap = true, silent = true })

-- 	end,
-- }
