-- return {
--     "kdheepak/lazygit.nvim",
--     config = function()
--         vim.keymap.set('n', '<leader>m', ':LazyGit<cr>', { noremap = true })
--     end
-- }
-- return {
--     "kdheepak/lazygit.nvim",
--     lazy = true,
--     cmd = {
--         "LazyGit",
--         "LazyGitConfig",
--         "LazyGitCurrentFile",
--         "LazyGitFilter",
--         "LazyGitFilterCurrentFile",
--     },
--     -- optional for floating window border decoration
--     dependencies = {
--         "nvim-lua/plenary.nvim",
--     },
--     -- setting the keybinding for LazyGit with 'keys' is recommended in
--     -- order to load the plugin when the command is run for the first time
--     keys = {
--         { "<leader>m", "<cmd>LazyGit<cr>", desc = "LazyGit" }
--     }
-- }
return {}
